baseURL = "https://qcarchive.molssi.org"
languageCode = "en-us"
title = "The MolSSI QCArchive"
theme = "small-apps-v2"
summaryLength = "10"
paginate = 6
pygmentsCodefences = true
pygmentsStyle = "solarized-dark"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themefisher-font/style.css"
  [[params.plugins.css]]
  URL = "plugins/owl-carousel/assets/owl.carousel.min.css"
  [[params.plugins.css]]
  URL = "plugins/owl-carousel/assets/owl.theme.green.min.css"
  [[params.plugins.css]]
  URL = "plugins/fancybox/jquery.fancybox.min.css"
  [[params.plugins.css]]
  URL = "plugins/aos/aos.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/owl-carousel/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "plugins/fancybox/jquery.fancybox.min.js"
  [[params.plugins.js]]
  URL = "plugins/syotimer/jquery.syotimer.min.js"
  [[params.plugins.js]]
  URL = "plugins/aos/aos.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"
  [[params.plugins.js]]
  URL = "plugins/particles/particles.min.js"

# navigation
[menu]
    

  [[menu.main]]
  name = "Get Started"
  URL = "/get_started"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "/blog"
  weight = 2
  

  [[menu.main]]
  weight = 3
  name = "Community"
  hasChildren = true

    [[menu.main]]
    parent = "Community"
    name = "Partners"
    URL = "/community"
    weight = 2

    [[menu.main]]
    parent = "Community"
    name = "Join Slack"
    URL = "https://join.slack.com/t/qcarchive/shared_invite/enQtNDIzNTQ2OTExODk0LTE3MWI0YzBjNzVhNzczNDM0ZTA5MmQ1ODcxYTc0YTA1ZDQ2MTk1NDhlMjhjMmQ0YWYwOGMzYzJkZTM2NDlmOGM"
    weight = 5

    [[menu.main]]
    parent = "Community"
    name = "Use Cases"
    URL = "/usecases"
    weight = 3

    [[menu.main]]
    parent = "Community"
    name = "Team"
    URL = "/team"
    weight = 4

    [[menu.main]]
    # parent = "Community"
    # name = "License and Funding"
    # URL = "/privacy"
    # weight = 20

  [[menu.main]]
  weight = 4
  name = "Examples"
  URL = "/examples"
  

[[menu.main]]
  weight = 9
  name = "Apps"
  hasChildren = true

#    [[menu.main]]
#    parent = "Apps"
#    name = "Reaction Datasets"
#    URL ="/apps/reaction_viewer"
#    weight = 1


    [[menu.main]]
    parent = "Apps"
    name = "Machine Learning Datasets"
#    URL = "https://dashapps.herokuapp.com/ml_datasets"
    URL = "/apps/ml_datasets"
    weight = 3


  [[menu.main]]
  name = "Infrastructure"
  URL = "https://docs.qcarchive.molssi.org"
  weight = 10
  pre = "<u>"
  post = "</u>"


  # footer menu
  [[menu.footer]]
  name = "Examples"
  URL = "/examples"
  weight = 1

  [[menu.footer]]
  name = "Get Started"
  URL = "/get_started"
  weight = 2

  [[menu.footer]]
  name = "Contact Us"
  URL = "mailto:qcarchive@molssi.org"
  # URL = "/contact"
  weight = 4

  [[menu.footer]]
  name = "License and Funding"
  URL = "/privacy"
  weight = 5


[params]
logo = "images/logo.png"
logoAlt = "images/logo-alt.png"
# home = "Home"
# Meta data
description = "MolSSI's QCArchive Project"
author = "The Molecular Sciences Software Institute"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "37.2001382,"
mapLongitude = "-80.4105687"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "UA-136219377-1"

  # Preloader
  [params.preloader]
  enable = true

# footer
  [params.footer]

  # social icon
  [[params.footer.socialIcon]]
  icon = "tf-ion-social-facebook"
  URL = "https://www.facebook.com/molssi/?fref=ts"

  [[params.footer.socialIcon]]
  icon = "tf-ion-social-twitter"
  URL = "https://twitter.com/MolSSI_NSF"
  
  [[params.footer.socialIcon]]
  icon = "tf-ion-social-linkedin"
  URL = "https://www.linkedin.com/groups/13503505/profile"

  # call to action
 [params.cta]
  enable = true
  title = "Help contribute to the QCArchive"
  content = "Want to see your code in QCArchive? Find a bug? Have questions in general? Head to the GitHub page and contribute!"
  btnText = "To QCArchive GitHub"
  URL = "https://github.com/MolSSI/QCFractal"

  # Community call to action
 [params.communitycta]
  enable = true
  title = "Become part of the QCArchive Community!"
  content = "Want to extend QCArchive to your projects? Want to wrap components in other code? Want to help contribute? Want to see what others are doing? Come be part of the QCArchive community today and lets make something greater!"
  btnText = "Join the QCArchive Slack!"
  URL = "https://join.slack.com/t/qcdb/shared_invite/enQtNDIzNTQ2OTExODk0LWM3OTgxN2ExYTlkMTlkZjA0OTExZDlmNGRlY2M4NWJlNDlkZGQyYWUxOTJmMzc3M2VlYzZjMjgxMDRkYzFmOTE"
